// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_health from "./routes/api/health.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_models from "./routes/api/models.ts";
import * as $api_voice from "./routes/api/voice.ts";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $ConversationHistory from "./islands/ConversationHistory.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $VoiceRecorder from "./islands/VoiceRecorder.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/health.ts": $api_health,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/models.ts": $api_models,
    "./routes/api/voice.ts": $api_voice,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/ConversationHistory.tsx": $ConversationHistory,
    "./islands/Counter.tsx": $Counter,
    "./islands/VoiceRecorder.tsx": $VoiceRecorder,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
